name: Build and Upload Artifact

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: corepack enable && pnpm install
      - name: Build project
        run: pnpm run build
      - name: Generate version
        run: pnpm version --no-git-tag-version "v0.0.0-experimental-$(git rev-parse --short HEAD)-$(date +%Y%m%d)"
      - name: Pack and Upload artifact
        run: pnpm pack
      - uses: actions/upload-artifact@v4
        with:
          name: package
          path: "*.tgz"
